### ISSUE TITLE
Allow to send command val

### ISSUE THREAD

**Issue by MaxiMaerz** [carzum/termviz#31]
Proposal:

Enter teleoperation mode and display it, e.g. press t from normal mode
Staying normal mode but enable sending command val:

Start sending while a button is pressed (e.g. x)
Send 0 on all directions while x i s pressed
accelerate by pressing  wsqe (forward backwards left right) and ad (rotate) each press increments the speed
if x is released, send 0

**Comment by Eman7C7** [comment]
How about:
- The default is view mode: wasd move the view with no effect on the robot
- t enters teleop mode, the view is centered on the robot and wasdqe drive the robot. 0 is sent  if nothing is pressed for safety
- e (I don't think we need to rotate the map, so it's probably free) enters send pose mode, the view centers on the robot and wasdqe move a "ghost" robot. Enter confirms and sends the pose, while esc resets the ghost (I wanted to implement this hopefully today as #8 if you and @carzum agree)

**Comment by carzum** [comment]
I like the idea to move the ghost robot, but we would probably also need to move the lasers to give direct feedback for alignment.
I think it would be best reserve  qe for teleop of omnidrive robots. Not moving when nothing is pressed is best and one could use an exponential curve mapped to the duration of a key being pressed for the velocity. (needs some experimenting)
Maybe m to toggle between the 3 modes? We can use the titlebar to show which mode is currently active
