### ISSUE TITLE
[Question][help]-Display extended Kalman filter(EKF) RMSE(Root mean Square Error values) in termviz?

### ISSUE THREAD

**Issue by anilbommareddy** [carzum/termviz#81]
Using Lidar and Rada Data i.e., sensor/imu data subscriber in ROS.
(a)Sensor Fusion-On these Lidar and Radar Data(senor/imu) will be calculated EKF-RMSE values.
(b) here to how display and visualise Lidar vs Radar vs output Data(Delta x and Y of Ladar like vechile movment and Radar & RMSE values- ROS environment like
   ["estimate_x"] = estimate(0); /* may be Delta X Lidar and Radar
   ["estimate_y"] = estimate(1); /* may be Delta Y-Lidar and Radar
   ["rmse_x"] =  RMSE(0);
    ["rmse_y"] =  RMSE(1);
     ["rmse_vx"] = RMSE(2);
     ["rmse_vy"] = RMSE(3);
 
For Reference here the example:

Input:
R 11.3365 -0.175531 0.442173 1477010508654756 11.3 -2 0.909855 2.72956
L 11.3424 -1.85113 1477010508709711 11.35 -1.85 0.909847 2.72953

radar ro:11.3365radar phi:-0.175531ro_dot:0.442173timestamp1477010508654756
estimation.size:1223
ground_truth.size:1223
rmse_x:465527 rmse_y:454346 rmse_vx812756 rmse_vy723024

estimate(0):8292.03estimate(1)26058.1

Laser x:11.3424 Laser y:-1.85113 timestamp 1477010508709711
estimation.size:1224
ground_truth.size:1224
rmse_x:465337 rmse_y:454161 rmse_vx812478 rmse_vy724231

estimate(0):9914.02estimate(1)26312.6

**Comment by MaxiMaerz** [comment]
You can display any graph within the supported topics (e.g. as a path).
Also, since very recently, you can publish a sphere marker around any point of your Graph which could show the RMS.

Please be aware, that Termviz is a visualization tool, the publication of said markers must be done by your side.
